baseURL = "https://nvtien98.github.io/"
languageCode = "en-us"
title = "ZaloPay Fresher Spring 2019 Technology"
theme = "minimal"
disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""
publishDir = "nvtien98.github.io"

[params]
    author = "Nguyễn Văn Tiến"
    githubUsername = "#"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 2

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "https://github.com/nvtien98"
    name = "github"
    weight = 1

[[menu.icon]]
    url = "https://www.facebook.com/vnTien02"
    name = "facebook"
    weight = 2

[[menu.icon]]
    url = "https://www.linkedin.com/in/nguyen-van-tien-18896113a/"
    name = "linkedin"
    weight = 3

